import { SUB_PROCESSORS } from "./sub-processors";

export interface PolicyInputs {
  businessName: string;
  businessUrl?: string | null;
  contactEmail: string;
  dataRegion: "eu" | "us" | "auto";
  retentionDaysConversations: number;
  retentionDaysLeads: number;
  leadCaptureEnabled: boolean;
  cookielessMode: boolean;
  effectiveDate: string; // ISO date yyyy-mm-dd
}

/**
 * Generate a Markdown privacy policy snippet tailored to the tenant's config.
 * This is NOT legal advice and must be reviewed by a qualified lawyer before use.
 *
 * The output is intended to be pasted into the business owner's existing privacy
 * policy page, or used as a starter when they don't yet have one.
 */
export function generatePrivacyPolicyMarkdown(inputs: PolicyInputs): string {
  const {
    businessName,
    businessUrl,
    contactEmail,
    dataRegion,
    retentionDaysConversations,
    retentionDaysLeads,
    leadCaptureEnabled,
    cookielessMode,
    effectiveDate,
  } = inputs;

  const regionSentence =
    dataRegion === "eu"
      ? "Chatbot data is stored in the European Union."
      : dataRegion === "us"
        ? "Chatbot data is stored in the United States."
        : "Chatbot data is stored in the region configured for your deployment.";

  const retentionSentence = (() => {
    const parts: string[] = [];
    if (retentionDaysConversations > 0) {
      parts.push(`chat transcripts for up to ${retentionDaysConversations} days`);
    } else {
      parts.push("chat transcripts indefinitely, unless you request deletion");
    }
    if (leadCaptureEnabled) {
      if (retentionDaysLeads > 0) {
        parts.push(`lead contact details for up to ${retentionDaysLeads} days`);
      } else {
        parts.push("lead contact details indefinitely, unless you request deletion");
      }
    }
    return parts.join(", and ");
  })();

  const cookieSentence = cookielessMode
    ? "The chatbot runs in cookie-free mode and stores only session-scoped state that is cleared when you close your browser tab. It does not set persistent cookies or identifiers."
    : "The chatbot stores a persistent visitor identifier in your browser using `localStorage`. This is used to remember your session and whether you previously dismissed the chat. It is not shared with any third party.";

  const leadCaptureSentence = leadCaptureEnabled
    ? `If you provide an email address or phone number to the chatbot, we may store it as a lead record so ${businessName} can follow up with you. You can request deletion at any time by contacting ${contactEmail}.`
    : "The chatbot does not ask for your email address or phone number unless the conversation clearly requires it (for example, to book an appointment).";

  const subProcessorBullets = SUB_PROCESSORS.map(
    (sp) =>
      `- **${sp.name}** (${sp.location}) — ${sp.purpose}. See their policy at [${sp.url.replace(/^https?:\/\//, "")}](${sp.url}).`,
  ).join("\n");

  const transferNote = SUB_PROCESSORS.some((sp) => sp.euResidency === "transfer")
    ? "Some of our processors (currently OpenAI and Anthropic) are located in the United States. When your messages are sent to them for language model processing, the data is transferred internationally under Standard Contractual Clauses approved by the European Commission."
    : "All of our sub-processors operate within our chosen data region.";

  const businessLine = businessUrl
    ? `This chatbot is operated by **${businessName}** ([${businessUrl.replace(/^https?:\/\//, "")}](${businessUrl}))`
    : `This chatbot is operated by **${businessName}**`;

  return `# Chatbot Privacy Notice

_Effective date: ${effectiveDate}_

${businessLine} using BizAssist, a third-party chatbot platform. This notice explains what data the chatbot collects, how it is used, how long it is kept, and what rights you have.

> **Not legal advice.** This snippet was generated from your chatbot configuration. It is a starting point and must be reviewed by a qualified lawyer before you publish it. It does not constitute a full privacy policy on its own.

## What we collect

When you chat with us, the following information is processed:

- **Messages you send** — the questions and text you type into the chat window.
- **Chatbot responses** — the replies generated by the AI assistant.
- **Technical metadata** — your approximate session, device type, language, and the page you were on when the chat opened.
${leadCaptureEnabled ? "- **Contact details** — email address, phone number, or name, but only if you voluntarily share them with the chatbot.\n" : ""}
## Why we process it

Your messages are processed to:

1. Generate AI responses to your questions,
2. Improve the quality of the chatbot's answers,
3. Detect abuse, spam, and safety incidents.

The legal basis under GDPR is our **legitimate interest** in providing customer support. Where you share contact details voluntarily, the legal basis is your **consent** or the **performance of a contract** at your request.

## Transparency notice (EU AI Act)

You are interacting with an AI system, not a human. Responses are generated automatically by a large language model. A human agent may take over the conversation if the chatbot cannot help.

## Where your data is stored

${regionSentence} ${transferNote}

## How long we keep it

We retain ${retentionSentence}. After that, the data is automatically deleted. You can request earlier deletion at any time.

## Cookies and local storage

${cookieSentence}

## Lead capture

${leadCaptureSentence}

## Sub-processors

The following third parties process your data on our behalf:

${subProcessorBullets}

## Your rights

Under GDPR, you have the right to:

- Access the data we hold about you,
- Rectify inaccurate data,
- Erase your data ("right to be forgotten"),
- Object to or restrict processing,
- Data portability (receive your data in a machine-readable format),
- Lodge a complaint with your national data protection authority.

To exercise any of these rights, email **${contactEmail}**. We will respond within 30 days.

## Human oversight

If you would prefer to speak to a human, type "talk to a human" in the chat or use the escalation option in the widget header.

---

_This notice was generated automatically from the BizAssist compliance configuration on ${effectiveDate}. Review and customise it before publishing._
`;
}
